#!/bin/bash


./ecs-metadata-collector --ecs-hosts <ecs-host1, ecs-host2> --ecs-access-key <ecs-admin-user-name> --ecs-secret-key <ecs-admin-password> --ecs-object-hosts <ecs-host1,ecs-host2> --ecs-mgmt-port 4443 --elastic-hosts <elastic-host-1, elastic-host-2> --elastic-port 9300 --elastic-cluster-name ecs-analytics --collect-data all